# Generated by Django 3.2.dev20201005102505 on 2020-12-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingDevice',
            fields=[
                ('deviceID', models.IntegerField(primary_key=True, serialize=False)),
                ('mfd', models.DateTimeField(auto_now_add=True, null=True)),
                ('warranty', models.DateTimeField(auto_now_add=True, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('dataID', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('timeRecorded', models.DateTimeField(auto_now_add=True, null=True)),
                ('deviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trackingdevice')),
            ],
        ),
    ]
