# Generated by Django 3.2.dev20201005102505 on 2020-12-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdevice',
            name='deviceName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='lattitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
