# Generated by Django 3.2.dev20201005102505 on 2020-12-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201213_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdata',
            name='deviceid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.trackingdevice'),
        ),
        migrations.AlterField(
            model_name='trackingdevice',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user'),
        ),
    ]
